[project]
name = "mayu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.11"
dependencies = [
    "fuzzywuzzy>=0.18.0",
    "gradio==5.49.1",
    "langgraph>=1.0.8",
    "openai>=2.18.0",
    "pandas==2.3.3",
    "textblob>=0.19.0",
]
